### ISSUE TITLE
This height does not changed when the height of the DOM node changes.

### ISSUE THREAD

**Issue by Koppel-Zhou** [iou90/react-native-autoheight-webview#68]
Some Images are lazy loaded in my page, The `<img />`'s height changed when these images are loaded, but `<AutoHeightWebView />`'s height does not changed. So, my page has been cut.

**Comment by ShaMan123** [comment]
Are the images static?
If they are, you could add them to your apps `assets` dir and then load them statically from the app.
I believe this will improve performance of the `<WebView>` and decrease laziness as well.

**Comment by ShaMan123** [comment]
Came up with an idea.
Try adding a `prop` to your  `<AutoHeightWebView>`:
 ```
customScript={()=>{
   someImg.onload=()=>{
      updateSize()     // read below
   }
}}
```

`updateSize()` is the function that triggers the entire `<AutoHeightWebView>` flow, starting with `window.postMessage()` and eventually setting the component's `state`.
It fires when the page loads and measures the `<WebView>`.
I think that the flow ends when `this.stopInterval()` is called 
(and maybe `setState({ isSizeChange: true })`).

Take a look at this folder: [./autoHeightWebView](https://github.com/iou90/react-native-autoheight-webview/tree/master/autoHeightWebView)

If I'm correct a PR is needed => adding a prop that flags a custom flow so that  `this.stopInterval()` will not get called before your condition is met **OR** restarting the flow by calling `this.startInterval() && this.finishInterval = false` 

```
<AutoHeightWebView
      customFlow
      customScript={
         someImg.onload=()=>{
            updateSize()     // read below
         }
      }
      />
```

I suggest you first try adding a `customScript`. Maybe it'll do the job.
If not, before going forward with a PR I would test this with a small POC => go to the code and comment the line `this.stopInterval()` in both `index.android.js` and `index.ios.js`  and see if the component behaves as desired.
